from __future__ import annotations

PATSTAT_TABLES = {
    "bronze_patstat_appln": ["tls201_appln"],
    "bronze_patstat_appln_title": ["tls202_appln_title"],
    "bronze_patstat_appln_abstr": ["tls203_appln_abstr"],
    "bronze_patstat_appln_prior": ["tls204_appln_prior"],
    "bronze_patstat_person": ["tls206_person"],
    "bronze_patstat_pers_appln": ["tls207_pers_appln"],
    "bronze_patstat_appln_ipc": ["tls209_appln_ipc"],
    "bronze_patstat_pat_publn": ["tls211_pat_publn"],
    "bronze_patstat_citation": ["tls212_citation"],
    "bronze_patstat_npl_publn": ["tls214_npl_publn"],
    "bronze_patstat_appln_contn": ["tls216_appln_contn"],
    "bronze_patstat_appln_cpc": ["tls224_appln_cpc"],
    "bronze_patstat_appln_techn_field": ["tls230_appln_techn_field", "tls230_appln_technfld"],
    "bronze_patstat_docdb_fam_citn": ["tls228_docdb_fam_citn"],
    "bronze_patstat_inpadoc_legal_event": ["tls231_inpadoc_legal_event", "tls221_inpadoc_prs"],
    "bronze_ref_legal_event_code": ["tls803_legal_event_code"],
}

REGISTER_TABLES = {
    "bronze_reg101_appln": ["reg101_appln"],
    "bronze_reg403_appln_status": ["reg403_appln_status"],
    "bronze_reg107_parties": ["reg107_parties"],
    "bronze_reg111_licensee": ["reg111_licensee"],
    "bronze_reg125_appeal": ["reg125_appeal"],
    "bronze_reg130_opponent": ["reg130_opponent"],
    "bronze_reg201_proc_step": ["reg201_proc_step"],
    "bronze_reg202_proc_step_text": ["reg202_proc_step_text"],
    "bronze_reg203_proc_step_date": ["reg203_proc_step_date"],
    "bronze_reg301_event_data": ["reg301_event_data"],
    "bronze_reg402_event_text": ["reg402_event_text"],
    "bronze_reg701_appln": ["reg701_appln"],
    "bronze_reg731_event_data": ["reg731_event_data"],
    "bronze_reg741_appln_status": ["reg741_appln_status"],
    "bronze_reg742_event_text": ["reg742_event_text"],
}

REFERENCE_TABLES = {
    "bronze_ref_techn_field_ipc": ["wipo_techn_field_ipc", "ipc_to_wipo_industry"],
    "bronze_ext_cpc_coverage": ["cpc_coverage"],
    "bronze_ext_cpc_ipc_weights": ["cpc_ipc_weights_2014_2025"],
    "bronze_ext_iso_country_map": ["iso_country_map", "country_iso_map"],
    "bronze_ext_world_bank_gdp_ppp": ["world_bank_gdp_ppp", "wb_gdp_ppp"],
    "bronze_ext_us_chamber_ip_index": ["us_chamber_ip_index", "ip_index"],
    "bronze_ext_up_member_states": ["up_member_states", "unitary_patent_member_states"],
    "bronze_ext_kind_code_normalization_seed": ["kind_code_normalization", "kind_code_normalization_seed"],
    "bronze_ext_oecd_indicator_seed": ["oecd_indicator_seed", "oecd_quality_indicator_seed"],
}

REQUIRED_SOURCE_COLUMNS = {
    "bronze_patstat_appln": ["appln_id", "docdb_family_id", "appln_auth"],
    "bronze_patstat_pat_publn": ["pat_publn_id", "appln_id", "publn_auth", "publn_kind"],
    "bronze_patstat_pers_appln": ["person_id", "appln_id"],
    "bronze_patstat_person": ["person_id"],
    "bronze_patstat_appln_ipc": ["appln_id", "ipc_class_symbol"],
    "bronze_patstat_appln_cpc": ["appln_id", "cpc_class_symbol"],
    "bronze_patstat_citation": ["pat_publn_id"],
    "bronze_patstat_appln_abstr": ["appln_id"],
    "bronze_patstat_appln_title": ["appln_id"],
    "bronze_patstat_appln_techn_field": ["appln_id"],
    "bronze_patstat_inpadoc_legal_event": ["appln_id"],
    "bronze_ref_techn_field_ipc": ["techn_field"],
    "bronze_ext_iso_country_map": ["iso2", "iso3"],
    "bronze_ext_world_bank_gdp_ppp": ["iso3", "snapshot_year", "gdp_value"],
    "bronze_ext_us_chamber_ip_index": ["iso2", "snapshot_year", "ip_score"],
    "bronze_ext_up_member_states": ["jurisdiction_code"],
    "bronze_ext_kind_code_normalization_seed": ["jurisdiction_code", "kind_code", "universal_stage", "stage_multiplier", "is_enforceable"],
    "bronze_ext_oecd_indicator_seed": ["indicator_name"],
    "bronze_reg101_appln": ["id", "appln_id"],
    "bronze_reg403_appln_status": ["status", "status_text"],
    "bronze_reg201_proc_step": ["id", "step_id"],
    "bronze_reg202_proc_step_text": ["step_id"],
    "bronze_reg203_proc_step_date": ["step_id"],
    "bronze_reg301_event_data": ["id", "event_code"],
    "bronze_reg402_event_text": ["event_code"],
    "bronze_reg701_appln": ["id"],
    "bronze_reg731_event_data": ["id", "event_code"],
    "bronze_reg741_appln_status": ["status"],
    "bronze_reg742_event_text": ["event_code"],
}
