from config.settings import get_settings


def get_parquet_registry() -> dict[str, str]:
    base = get_settings().parquet_base_url
    return {
        "patent_core": f"{base}/patent_core.parquet",
        "patent_core_w_ranks": f"{base}/patent_core_with_ranks.parquet",
        "patent_tech_market_axes": f"{base}/patent_tech_market_axes.parquet",
        "patent_tech_lens_presence": f"{base}/patent_tech_lens_presence.parquet",
        "patent_tech_lens_freq": f"{base}/patent_tech_lens_freq_v3.parquet",
        "patent_industry_presence": f"{base}/patent_industry_presence.parquet",
        "patent_industry_freq": f"{base}/patent_industry_freq.parquet",
        "patent_portfolio_map": f"{base}/patent_portfolio_map.parquet",
        "patent_frequency_scores": f"{base}/patent_frequency_scores.parquet",
        "patent_final_decision_scores": f"{base}/patent_final_decision_scores.parquet",
        "patent_final_decision_scores_ui": f"{base}/patent_final_decision_scores_ui.parquet",
        "patent_rank_global": f"{base}/patent_rank_global.parquet",
        "patent_rank_in_tech": f"{base}/patent_rank_in_tech.parquet",
        "patent_citation_events_core": f"{base}/patent_citation_events_core.parquet",
        "patent_citation_events_yearly": f"{base}/patent_citation_events_yearly.parquet",
        "patent_citation_metrics": f"{base}/patent_citation_metrics.parquet",
        "portfolio_citation_timeseries": f"{base}/portfolio_citation_timeseries.parquet",
        "portfolio_citation_metrics": f"{base}/portfolio_citation_metrics.parquet",
        "portfolio_axis_scores": f"{base}/portfolio_axis_scores.parquet",
        "portfolio_master": f"{base}/portfolio_master.parquet",
        "portfolio_peer_benchmark": f"{base}/portfolio_peer_benchmark.parquet",
        "portfolio_ranking_final": f"{base}/portfolio_ranking_final.parquet",
        "portfolio_size_reference": f"{base}/portfolio_size_reference.parquet",
        "owner_reference": f"{base}/owner_reference.parquet",
        "portfolio_final": f"{base}/portfolio_final.parquet",
        "portfolio_cpc_stats": f"{base}/portfolio_cpc_distribution_stats.parquet",
        "portfolio_industry_stats": f"{base}/portfolio_industry_distribution_stats.parquet",
        "portfolio_cpc": f"{base}/portfolio_cpc_distribution.parquet",
        "portfolio_industry": f"{base}/portfolio_industry_distribution.parquet",
        "portfolio_licensing": f"{base}/portfolio_licensing_final.parquet",
        "family_members": f"{base}/family_members.parquet",
        "raw_family_grants": f"{base}/raw_family_grants.parquet",
        "family_grants": f"{base}/family_grants.parquet",
        "raw_family_cpc": f"{base}/raw_family_cpc.parquet",
        "family_cpc": f"{base}/family_cpc.parquet",
        "family_members_metrics": f"{base}/family_members_metrics.parquet",
        "family_grant_metrics": f"{base}/family_grant_metrics.parquet",
        "family_cpc_metrics": f"{base}/family_cpc_metrics.parquet",
        "patent_family_enriched": f"{base}/patent_family_enriched.parquet",
        "portfolio_family_metrics": f"{base}/portfolio_family_metrics.parquet",
        "portfolio_family_grant_mix": f"{base}/portfolio_family_grant_mix.parquet",
        "portfolio_family_top_cpcs": f"{base}/portfolio_family_top_cpcs.parquet",
        "portfolio_family_assets": f"{base}/portfolio_family_assets.parquet",
        "ml_training_table": f"{base}/ml_patent_training_table.parquet",
    }
